### ISSUE TITLE
Reference all information

### ISSUE THREAD

**Issue by Echolon** [xsf/xmpp-providers-website#2]
Reference all information with the respective source in the json file so user and devs see where we got the information from

**Comment by cal0pteryx** [comment]
This would need additional processing of `providers.json`. Best would be to provide this file on https://data.xmpp.net/ as well.

**Comment by melvo** [comment]
I created xsf/infrastructure/pull/24 for that.

**Comment by cal0pteryx** [comment]
There is now an extended FAQ section about where properties are taken from: https://providers.xmpp.net/faq/#where-do-we-have-the-providers-properties-from

Also, all property sources are described here:
* https://invent.kde.org/melvo/xmpp-providers/-/tree/master#basic-information
* https://invent.kde.org/melvo/xmpp-providers/-/tree/master#criteria
