### ISSUE TITLE
Feature request: add "green" information

### ISSUE THREAD

**Issue by nieebel** [xsf/xmpp-providers-website#42]
It would be awesome if one could directly see if the server is hosted green :)
https://www.thegreenwebfoundation.org/ is providing an API for that. Similar as the greenfediverse project is doing it: https://greenfediverse.codeberg.page/green-instances/

**Comment by Echolon** [comment]
Hey @nieebel,

many thanks for the suggestion.

@wurstsalat3000 @melvo I think that is a topic we should discuss in the next meeting first before giving more feedback.

**Comment by wurstsalat3000** [comment]
Moved to https://invent.kde.org/melvo/xmpp-providers/-/issues/71

**Comment by melvo** [comment]
@nieebel We [added that information](https://fosstodon.org/@xmpp_providers/110802431627220360) and it is updated daily now. It is listed for each provider on their details page, e.g., on https://providers.xmpp.net/provider/magicbroccoli.de/.  Thanks again for your idea!
