### ISSUE TITLE
`groupChatSupport` rendered wrongly

### ISSUE THREAD

**Issue by Yuubi-san** [xsf/xmpp-providers-website#43]
The URIs in HTML look like this: `xmpp:[support@chat.hookipa.net]?join`.

Looking at [the data](https://invent.kde.org/melvo/xmpp-providers/-/raw/master/providers.json), seems it's an array of strings, not a single string.

**Comment by Yuubi-san** [comment]
Another thing is: I don't think the JID is being URI-escaped in the formatting code, which will pose additional problems in rare corner cases.  My pet peeve is JIDs with a # in the localpart (which is perfectly cromulent) put directly into URIs, resulting in jid's premature termination, # being the start of uri fragment. :)

**Comment by wurstsalat3000** [comment]
Rendering has been fixed in f369bbd911ba54ac9f8eda3641db1f68b2f6ffa3

**Comment by wurstsalat3000** [comment]
I tried this with `#` in an address, but it has been transferred to my XMPP client just fine.

**Comment by Yuubi-san** [comment]
Sure it transfers, but what does the client do with it?  It's supposed to take the path part as the JID, but... Let's try with some parsers:
```
$ python3.7 -q
>>> import urllib.parse
>>> urllib.parse.urlparse('xmpp:foo#bar@baz.tld')
ParseResult(scheme='xmpp', netloc='', path='foo', params='', query='', fragment='bar@baz.tld')
>>>
$ lua
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> for k,v in pairs(require'socket.url'.parse('xmpp:foo#bar@baz.tld')) do print(k,v) end
scheme  xmpp
fragment        bar@baz.tld
path    foo
>
```
Finally, if I put `<a href='xmpp:foo#bar@baz.tld'>click me</a>` into an .html file, open that in stock Android html viewer and tap the link, Conversations rightfully prompts me to add 'foo' as a contact.

Even more fun when you try with a JID like `foo%bar@baz.tld` (just as valid according to XEP-0106), i.e. `<a href='xmpp:foo%bar@baz.tld'>click me</a>`.  Java swallows the invalid UTF-8 for breakfast, so Conv. asks to add foo�r@baz.tld to my roster. :) The XEP even menstions:
> the % character is an often-used character in existing JIDs (e.g., to replace the @ character in gateway addresses)

**Comment by Yuubi-san** [comment]
The escaping burden could have been put on the maintainers of the data (by putting full uris there, not jids), but changing the format at this point is probably unfeasable.

**Comment by Yuubi-san** [comment]
\o/
