### ISSUE TITLE
problem with omemo key sharing for nixnet.services users in encrypted groups

### ISSUE THREAD

**Issue by pravi** [xsf/xmpp-providers-website#46]
nixnet.services is listed as category A provider but their users have problems with omemo key sharing in encrypted groups. May be we should explicitly check omemo key sharing of users in encrypted private groups which are not in contacts. This completely breaks the encrypted chat as no one else can send any message in this group until that user is removed.

**Comment by wurstsalat3000** [comment]
Thanks for your suggestion! Since this topic concerns the list providers.xmpp.net is based on, but not the website itself, I moved this issue to https://invent.kde.org/melvo/xmpp-providers/-/issues/54
