### ISSUE TITLE
Improve build caching

### ISSUE THREAD

**Issue by mwild1** [xsf/xmpp-providers-website#67]
Hi,

When using the docker approach for building and deploying the site, docker uses the checksum of ADD/COPY-added files to determine whether a layer is in the cache or not.

This means, if the website in the repo changes, docker will correctly rebuild the final image.

However, if *only* the upstream providers data changes, docker cannot see this - because that data is only fetched during building (by `tools/prepare.py`).

My recommendation would be to not download stuff in the script, but use ADD with a https:// URL (e.g. from data.xmpp.net) instead to have docker download the file for you, and check if it has changed.

**Comment by wurstsalat3000** [comment]
Thanks for digging into this issue! I hope my fix correctly implements what you suggested.
