### ISSUE TITLE
Allow running outside of providers.xmpp.net

### ISSUE THREAD

**Issue by mwild1** [xsf/xmpp-providers-website#68]
This is a relatively low-priority issue, but it would be nice to have and shouldn't be too difficult.

Running a (working) copy of the website locally or elsewhere (not at providers.xmpp.net) is more difficult than it should be. There are two options to fix it:

- Use relative paths to resources, these include:
  - `https://providers.xmpp.net/css/bootstrap.min.css`
  - `https://providers.xmpp.net/css/style.min.css`
  - `https://providers.xmpp.net/fontawesome/css/all.min.css`
- Alternatively, allow overriding the baseURL config during the build process. This could be done by using a docker build arg, and passing the `-b` flag to hugo when building.

**Comment by wurstsalat3000** [comment]
You can now override Hugo's baseURL while building the Docker image by using `--build-arg BASEURL=url`:

```bash
docker build -t xmpp-providers --build-arg BASEURL=http://localhost/ -f ./Dockerfile .
```
