### ISSUE TITLE
Incorrect rendering: National flag of Switzerland

### ISSUE THREAD

**Issue by MrEddX** [xsf/xmpp-providers-website#91]
- Tried it in several web browsers and devices and here's the result:

![image](https://github.com/user-attachments/assets/3a879484-b32d-4ce8-9846-90232e254d9a)

- The correct image should be:

![image](https://github.com/user-attachments/assets/d8808e8a-3e9c-4544-a518-7711cd178e97)

- Address used as an example: https://providers.xmpp.net/provider/chatrix.one/

Could you please confirm?
Thanks.

**Comment by cal0pteryx** [comment]
Hi, you need to specify correct entries in your provider file's `serverLocation`. If your server is located in Switzerland, you would need to specify "ch" there. At the moment I only see ["sz", "bg"].

Does this answer your question?

Am 16. Juli 2024 11:54:11 MESZ schrieb MrEddX ***@***.***>:

**Comment by MrEddX** [comment]
You're absolutely right!
Just an error, during the country selection from the menu. Swaziland was chosen instead of Switzerland. It's fixed now!

Thank You!
